export const RECEIVE_BILLS = 'RECEIVE_BILLS'
export const RECEIVE_SENATORS = 'RECEIVE_SENATORS'
export const RECEIVE_VOTES_FOR_BILL = 'RECEIVE_VOTES_FOR_BILL'
export const RECEIVE_VOTE = 'RECEIVE_VOTE'
